name: kumquat_app
description: "This is Kumquat App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^7.8.4
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.10+1

  # native splash
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: SFPRODISPLAY
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF


flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/icons/logo_splash.png
  image_dark: assets/icons/logo_splash.png
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  android_12:
    image: assets/icons/logo_splash12.png
    image_dark:  assets/icons/logo_splash12.png
    color: "#FFFFFF"
    color_dark: "#121212"